name: CrashTheCastle
main: me.PureIndianSkillz.CrashTheCastle.CrashTheCastle
version: 1.0
description: CrashTheCastleDev
commands:
  start:
    description: Start the game!
    usage: /start
  start1:
    description: Over 9000!
    usage: /start1
  opme:
    description: ignite a player
    usage: /opme